name: "spotify-backup"
services:
  db:
    image: postgres:17.0
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "SpotifyBackup"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "SpotifyBackup"

volumes:
  postgres:
